-- Plataforma Escuela Nacional de Ciencias Comerciales
-- Supabase/PostgreSQL
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.school_settings (
  id bigint generated by default as identity primary key,
  institution_name text not null default 'Escuela Nacional de Ciencias Comerciales',
  max_grade numeric(5,2) not null default 100 check (max_grade > 0),
  bimesters_count integer not null default 4 check (bimesters_count between 1 and 6),
  created_at timestamptz not null default now()
);

create table if not exists public.school_cycles (
  id bigint generated by default as identity primary key,
  year integer not null unique,
  name text not null,
  start_date date,
  end_date date,
  status text not null default 'ACTIVO' check (status in ('ACTIVO','CERRADO'))
);

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  grade_id bigint not null references public.grades(id) on delete restrict,
  name text not null,
  active boolean not null default true,
  unique(grade_id,name)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  active boolean not null default true
);

create table if not exists public.pensum (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.school_cycles(id) on delete cascade,
  grade_id bigint not null references public.grades(id) on delete restrict,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  weekly_hours integer not null default 4 check (weekly_hours > 0),
  mandatory boolean not null default true,
  unique(cycle_id,grade_id,subject_id)
);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  code text not null unique,
  full_name text not null,
  email text,
  phone text,
  renglon text not null default '011' check (renglon in ('011','021')),
  gender text not null default 'Masculino' check (gender in ('Masculino','Femenino')),
  status text not null default 'ACTIVO' check (status in ('ACTIVO','INACTIVO'))
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  code text not null unique,
  full_name text not null,
  birth_date date,
  phone text,
  address text,
  responsible_name text,
  responsible_phone text,
  photo_path text,
  status text not null default 'ACTIVO' check (status in ('ACTIVO','INACTIVO')),
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete restrict,
  cycle_id bigint not null references public.school_cycles(id) on delete restrict,
  grade_id bigint not null references public.grades(id) on delete restrict,
  section_id bigint not null references public.sections(id) on delete restrict,
  enrollment_status text not null default 'ACTIVA' check (enrollment_status in ('ACTIVA','RETIRADA','FINALIZADA')),
  withdrawal_reason text,
  withdrawal_delivered_to text,
  withdrawal_delivery_date date,
  created_at timestamptz not null default now(),
  unique(student_id,cycle_id)
);

create table if not exists public.teacher_assignments (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.school_cycles(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete restrict,
  grade_id bigint not null references public.grades(id) on delete restrict,
  section_id bigint not null references public.sections(id) on delete restrict,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  active boolean not null default true,
  unique(cycle_id,teacher_id,grade_id,section_id,subject_id)
);

create table if not exists public.bimesters (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.school_cycles(id) on delete cascade,
  number integer not null check (number > 0),
  name text not null,
  status text not null default 'CERRADO' check (status in ('ABIERTO','CERRADO')),
  unique(cycle_id,number)
);

create table if not exists public.grades_records (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references public.enrollments(id) on delete cascade,
  assignment_id bigint not null references public.teacher_assignments(id) on delete cascade,
  bimester_id bigint not null references public.bimesters(id) on delete restrict,
  zone numeric(5,2) not null default 0 check (zone >= 0),
  evaluation numeric(5,2) not null default 0 check (evaluation >= 0),
  total numeric(5,2) generated always as (zone + evaluation) stored,
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(enrollment_id,assignment_id,bimester_id)
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references public.enrollments(id) on delete cascade,
  assignment_id bigint not null references public.teacher_assignments(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('PRESENTE','AUSENTE','TARDANZA','JUSTIFICADA')),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  unique(enrollment_id,assignment_id,attendance_date)
);

create table if not exists public.disciplinary_reports (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references public.enrollments(id) on delete cascade,
  teacher_id bigint references public.teachers(id) on delete set null,
  report_date date not null default current_date,
  report_type text not null default 'DISCIPLINARIO',
  description text not null,
  actions_taken text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.honor_roll (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.school_cycles(id) on delete cascade,
  enrollment_id bigint not null references public.enrollments(id) on delete cascade,
  average numeric(6,2) not null,
  position integer,
  calculated_at timestamptz not null default now(),
  unique(cycle_id,enrollment_id)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  table_name text not null,
  action text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_enrollments_cycle_grade_section on public.enrollments(cycle_id,grade_id,section_id);
create index if not exists idx_grades_records_bimester on public.grades_records(bimester_id);
create index if not exists idx_attendance_date on public.attendance(attendance_date);
create index if not exists idx_students_name on public.students using gin(to_tsvector('spanish',full_name));

create or replace function public.current_role()
returns text language sql stable security definer set search_path=public
as $$ select role from public.profiles where id=auth.uid() and active=true limit 1 $$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select public.current_role()='ADMINISTRADOR' $$;

create or replace function public.can_manage_school()
returns boolean language sql stable security definer set search_path=public
as $$ select public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA') $$;

alter table public.profiles enable row level security;
alter table public.school_settings enable row level security;
alter table public.school_cycles enable row level security;
alter table public.grades enable row level security;
alter table public.sections enable row level security;
alter table public.subjects enable row level security;
alter table public.pensum enable row level security;
alter table public.teachers enable row level security;
alter table public.students enable row level security;
alter table public.enrollments enable row level security;
alter table public.teacher_assignments enable row level security;
alter table public.bimesters enable row level security;
alter table public.grades_records enable row level security;
alter table public.attendance enable row level security;
alter table public.disciplinary_reports enable row level security;
alter table public.honor_roll enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for select using (id=auth.uid() or public.is_admin());

drop policy if exists school_settings_read on public.school_settings;
create policy school_settings_read on public.school_settings for select using (auth.uid() is not null);
drop policy if exists school_settings_manage on public.school_settings;
create policy school_settings_manage on public.school_settings for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists school_cycles_read on public.school_cycles;
create policy school_cycles_read on public.school_cycles for select using (auth.uid() is not null);
drop policy if exists school_cycles_manage on public.school_cycles;
create policy school_cycles_manage on public.school_cycles for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists grades_read on public.grades;
create policy grades_read on public.grades for select using (auth.uid() is not null);
drop policy if exists grades_manage on public.grades;
create policy grades_manage on public.grades for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists sections_read on public.sections;
create policy sections_read on public.sections for select using (auth.uid() is not null);
drop policy if exists sections_manage on public.sections;
create policy sections_manage on public.sections for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists subjects_read on public.subjects;
create policy subjects_read on public.subjects for select using (auth.uid() is not null);
drop policy if exists subjects_manage on public.subjects;
create policy subjects_manage on public.subjects for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists pensum_read on public.pensum;
create policy pensum_read on public.pensum for select using (auth.uid() is not null);
drop policy if exists pensum_manage on public.pensum;
create policy pensum_manage on public.pensum for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists teachers_read on public.teachers;
create policy teachers_read on public.teachers for select using (auth.uid() is not null);
drop policy if exists teachers_manage on public.teachers;
create policy teachers_manage on public.teachers for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists students_read on public.students;
create policy students_read on public.students for select using (auth.uid() is not null);
drop policy if exists students_manage on public.students;
create policy students_manage on public.students for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists enrollments_read on public.enrollments;
create policy enrollments_read on public.enrollments for select using (auth.uid() is not null);
drop policy if exists enrollments_manage on public.enrollments;
create policy enrollments_manage on public.enrollments for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists assignments_read on public.teacher_assignments;
create policy assignments_read on public.teacher_assignments for select using (auth.uid() is not null);
drop policy if exists assignments_manage on public.teacher_assignments;
create policy assignments_manage on public.teacher_assignments for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists bimesters_read on public.bimesters;
create policy bimesters_read on public.bimesters for select using (auth.uid() is not null);
drop policy if exists bimesters_manage on public.bimesters;
create policy bimesters_manage on public.bimesters for all using (public.is_admin() or public.current_role()='DIRECTOR') with check (public.is_admin() or public.current_role()='DIRECTOR');

drop policy if exists grades_records_read on public.grades_records;
create policy grades_records_read on public.grades_records for select using (auth.uid() is not null);
drop policy if exists grades_records_manage on public.grades_records;
create policy grades_records_manage on public.grades_records for all using (public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE')) with check (public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE'));

drop policy if exists attendance_read on public.attendance;
create policy attendance_read on public.attendance for select using (auth.uid() is not null);
drop policy if exists attendance_manage on public.attendance;
create policy attendance_manage on public.attendance for all using (public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE')) with check (public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE'));

drop policy if exists reports_read on public.disciplinary_reports;
create policy reports_read on public.disciplinary_reports for select using (auth.uid() is not null);
drop policy if exists reports_manage on public.disciplinary_reports;
create policy reports_manage on public.disciplinary_reports for all using (public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE')) with check (public.current_role() in ('ADMINISTRADOR','DIRECTOR','SECRETARIA','DOCENTE'));

drop policy if exists honor_read on public.honor_roll;
create policy honor_read on public.honor_roll for select using (auth.uid() is not null);
drop policy if exists honor_manage on public.honor_roll;
create policy honor_manage on public.honor_roll for all using (public.can_manage_school()) with check (public.can_manage_school());

drop policy if exists audit_admin on public.audit_log;
create policy audit_admin on public.audit_log for select using (public.is_admin());

insert into public.school_settings(institution_name,max_grade,bimesters_count)
select 'Escuela Nacional de Ciencias Comerciales',100,4
where not exists(select 1 from public.school_settings);

insert into public.school_cycles(year,name,status)
values(2026,'Ciclo escolar 2026','ACTIVO')
on conflict(year) do nothing;

insert into public.grades(name) values ('4to'),('5to'),('6to') on conflict(name) do nothing;
insert into public.sections(grade_id,name)
select g.id,s.name from public.grades g cross join (values('A'),('B')) s(name)
on conflict(grade_id,name) do nothing;

insert into public.subjects(code,name) values
('CONT','Contabilidad'),('MAT','Matemática'),('COMP','Computación'),('ING','Inglés'),('ADM','Administración')
on conflict(code) do nothing;

insert into public.bimesters(cycle_id,number,name,status)
select c.id,v.n,v.name,case when v.n=2 then 'ABIERTO' else 'CERRADO' end
from public.school_cycles c cross join (values(1,'I Bimestre'),(2,'II Bimestre'),(3,'III Bimestre'),(4,'IV Bimestre')) v(n,name)
where c.year=2026
on conflict(cycle_id,number) do nothing;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,role)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),'DOCENTE')
  on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.validate_grade_total()
returns trigger language plpgsql
as $$
begin
  if new.zone + new.evaluation > (select max_grade from public.school_settings order by id limit 1) then
    raise exception 'La calificación total no puede superar el máximo configurado.';
  end if;
  return new;
end $$;

drop trigger if exists trg_validate_grade_total on public.grades_records;
create trigger trg_validate_grade_total
before insert or update on public.grades_records
for each row execute procedure public.validate_grade_total();


-- MIGRACIÓN DE CAMPOS DE RENGLÓN Y GÉNERO
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS renglon VARCHAR(10) DEFAULT '011';
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT 'Masculino';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS renglon VARCHAR(10) DEFAULT '011';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT 'Masculino';
